version: '3'

services:
  erpnext-nginx:
    image: frappe/erpnext-nginx:v14
    restart: always
    ports:
      - "8080:80"
    volumes:
      - sites:/var/www/html/sites
      - logs:/var/log
    depends_on:
      - erpnext-python

  erpnext-python:
    image: frappe/erpnext-worker:v14
    restart: always
    environment:
      - MARIADB_HOST=erpnext-mariadb
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  erpnext-mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=erpnext
      - MYSQL_PASSWORD=erpnext
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis-cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-socketio-data:/data

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites:
  logs: 